name: UnifiedMetrics
main: dev.cubxity.plugins.metrics.bukkit.bootstrap.UnifiedMetricsBukkitBootstrap
description: "Fully-featured metrics plugin for Minecraft servers"
api-version: 1.16
author: Cubxity
version: ${version}
load: STARTUP

depend:
  - shungite